# Generated by Django 4.2.8 on 2023-12-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Activeness status'),
        ),
    ]
