# Generated by Django 4.2.8 on 2023-12-16 12:18

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Category')),
                ('slug', models.SlugField(unique=True, verbose_name='Identificator')),
                ('description', models.CharField(max_length=255, verbose_name='Short Description')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Long Description')),
                ('image', django_resized.forms.ResizedImageField(crop=None, default='category_pics/default.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[1920, 1080], upload_to='category_pics/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(max_length=255, verbose_name='Short Description')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Long Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Price')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('image', django_resized.forms.ResizedImageField(crop=None, default='product_pics/default.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[1920, 1080], upload_to='product_pics/', verbose_name='Image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
            },
        ),
    ]
