# Generated by Django 4.2.8 on 2023-12-17 17:34

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='category_pics/default.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 500], upload_to='category_pics/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='product_pics/default.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[540, 360], upload_to='product_pics/', verbose_name='Image'),
        ),
    ]
