# Generated by Django 4.2.8 on 2023-12-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_created_at_category_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='12', unique=True, verbose_name='Identificator'),
        ),
    ]
