# Generated by Django 4.2.8 on 2023-12-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_productcartitem_quantity_userreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReview',
        ),
    ]
