# Generated by Django 4.2.8 on 2023-12-22 12:11

import ckeditor.fields
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_userreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(max_length=600, verbose_name='Short description')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Content of detail page')),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('image', django_resized.forms.ResizedImageField(crop=None, default='page_pics/default.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[540, 419], upload_to='page_pics/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Main Page',
            },
        ),
    ]
